In [2]:
import pandas as pd
import ta

In [377]:
data = pd.read_csv('datasets/49_Industry_Portfolios_Daily.csv',skiprows=[0,1,2,3,4,5,6,7,8])

/Users/garvin/opt/anaconda3/envs/refinda/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3251: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [378]:
data

,Unnamed: 0,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,...,Boxes,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other
0,19260701,0.56,-0.07,-99.99,-1.39,0.0,-1.44,0.62,-1.27,-0.9,...,-0.93,0.14,2.77,-0.02,0.27,0.59,0.47,0.81,0.57,-1.66
1,19260702,0.29,0.06,-99.99,0.78,0.7,1.46,0.03,0.0,-0.34,...,1.07,0.07,0.0,0.01,-0.1,1.04,-0.03,-0.61,-1.03,3.09
2,19260706,-0.33,0.18,-99.99,-1.74,0.5,-0.96,-0.06,4.27,-1.2,...,0.73,-0.2,0.77,-0.22,-0.67,0.45,0.31,-0.72,0.62,1.41
3,19260707,3.57,-0.15,-99.99,-1.73,-0.12,-0.49,-0.06,-4.1,-0.22,...,2.22,0.18,-3.21,-0.57,-0.7,-1.09,0.21,0.07,0.17,0.62
4,19260708,0.3,1.12,-99.99,-0.15,0.3,-0.49,0.24,0.0,-0.01,...,-0.39,0.46,-1.1,-0.38,0.33,0.99,-0.88,-0.36,-1.1,0.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50250,20211124,-0.03,-0.18,2.19,-0.37,-0.28,0.91,1.01,0.32,0.22,...,-1.04,-0.09,0.35,-1.29,0.14,-0.1,-0.18,0.45,0.35,1.44
50251,20211126,-2.58,-1.97,-1.81,-0.95,-0.52,-1.38,-2.72,-2.69,-2.25,...,-0.9,-3.85,-2.77,-2.42,-3.0,-3.48,-2.78,-3.08,-3.17,-0.83
50252,20211129,-1.74,-0.83,-1.69,-0.02,-0.94,-1.73,-1.15,0.57,-1.03,...,-0.94,-0.42,-0.58,-0.66,-1.39,-0.47,-0.86,0.05,0.2,-0.07
50253,20211130,-1.99,-1.99,-3.0,-2.12,-0.55,-1.35,-2.03,-0.95,-2.4,...,-3.83,-2.7,-2.72,-2.5,-1.93,-1.28,-2.16,-1.75,-2.73,-0.35
50254,Copyright 2021 Kenneth R. French,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [379]:
#exclude last entry indicating coopyrights
data = data.iloc[0:data.shape[0]-1]

#create date variable
data['Date'] = data.iloc[:,0]
#data['Index'] =  [i for i in range(data.shape[0])]


#drop unnamed column
data = data.drop(['Unnamed: 0'],axis=1)

/var/folders/2x/7wn1l7k91xz4_hvz4h1mpz500000gn/T/ipykernel_49328/3640712619.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Date'] = data.iloc[:,0]

In [380]:
data.shape

(50254, 50)

In [381]:

#select equally weighted
data = data.iloc[25128:data.shape[0]]
data = data.reset_index()

In [382]:
data

,index,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,...,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other,Date
0,25128,0.63,-0.28,-99.99,-0.74,-0.04,-1.44,0.57,-1.27,-0.59,...,0.29,1.50,-0.13,-0.22,2.26,0.54,1.46,-0.11,-0.75,19260701
1,25129,1.03,0.11,-99.99,0.09,0.40,1.46,0.18,0.00,0.17,...,-0.51,0.00,-0.06,-0.86,0.94,-0.19,2.10,-0.68,2.47,19260702
2,25130,-1.26,-0.12,-99.99,-0.25,0.63,-0.96,0.09,4.27,-0.28,...,0.21,0.42,0.17,-0.28,0.25,0.69,-0.41,0.69,0.66,19260706
3,25131,1.55,-0.43,-99.99,-2.02,-0.76,-0.49,0.11,-4.10,-0.06,...,-0.14,-7.24,-0.41,-0.72,-0.84,0.13,-2.24,-0.41,0.41,19260707
4,25132,0.95,1.01,-99.99,-0.08,1.00,-0.49,-0.01,0.00,0.18,...,0.18,2.56,-0.29,-0.04,0.74,-0.83,-0.21,-1.15,-0.60,19260708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25121,50249,0.16,-0.04,-4.0,0.57,0.36,-2.51,-0.99,0.32,-0.57,...,-0.21,-0.14,-1.19,-0.6,0.65,0.09,-0.08,0.03,-0.22,20211123
25122,50250,-0.03,-0.18,2.19,-0.37,-0.28,0.91,1.01,0.32,0.22,...,-0.09,0.35,-1.29,0.14,-0.1,-0.18,0.45,0.35,1.44,20211124
25123,50251,-2.58,-1.97,-1.81,-0.95,-0.52,-1.38,-2.72,-2.69,-2.25,...,-3.85,-2.77,-2.42,-3.0,-3.48,-2.78,-3.08,-3.17,-0.83,20211126
25124,50252,-1.74,-0.83,-1.69,-0.02,-0.94,-1.73,-1.15,0.57,-1.03,...,-0.42,-0.58,-0.66,-1.39,-0.47,-0.86,0.05,0.2,-0.07,20211129
25125,50253,-1.99,-1.99,-3.0,-2.12,-0.55,-1.35,-2.03,-0.95,-2.4,...,-2.7,-2.72,-2.5,-1.93,-1.28,-2.16,-1.75,-2.73,-0.35,20211130

In [383]:
#converts all entries into floats and Date variable into TimeStemp
from datetime import datetime

for col in data.columns:
    if col != 'Date':
        data[col] = [float(str(x).strip()) for x in data[col].values]
    else:
        data[col] = [datetime.strptime(str(x).strip(), '%Y%m%d') for x in data[col].values]

In [384]:
data.head()

,index,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,...,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other,Date
0,25128.0,0.63,-0.28,-99.99,-0.74,-0.04,-1.44,0.57,-1.27,-0.59,...,0.29,1.50,-0.13,-0.22,2.26,0.54,1.46,-0.11,-0.75,1926-07-01
1,25129.0,1.03,0.11,-99.99,0.09,0.40,1.46,0.18,0.00,0.17,...,-0.51,0.00,-0.06,-0.86,0.94,-0.19,2.10,-0.68,2.47,1926-07-02
2,25130.0,-1.26,-0.12,-99.99,-0.25,0.63,-0.96,0.09,4.27,-0.28,...,0.21,0.42,0.17,-0.28,0.25,0.69,-0.41,0.69,0.66,1926-07-06
3,25131.0,1.55,-0.43,-99.99,-2.02,-0.76,-0.49,0.11,-4.10,-0.06,...,-0.14,-7.24,-0.41,-0.72,-0.84,0.13,-2.24,-0.41,0.41,1926-07-07
4,25132.0,0.95,1.01,-99.99,-0.08,1.00,-0.49,-0.01,0.00,0.18,...,0.18,2.56,-0.29,-0.04,0.74,-0.83,-0.21,-1.15,-0.60,1926-07-08

In [385]:
#make sure, no NA values present 
data.isnull().values.any()

False

In [386]:

#Restric data to >= 1969-07-01 as this is the first months with data availabiltiy for all 49 portfolios
data = data.loc[data['Date']>='1969-07-01',:]

In [387]:
def convert_prices(dailyReturns,start=100):


    '''

    @param dailyReturns vector of returns

    @return vector of prices
    '''

    df=pd.DataFrame({'dailyReturns':dailyReturns})
    df['close'] = start * (1 + df['dailyReturns']/100).cumprod()

    return df['close']

In [388]:
import numpy as np

In [389]:
data.shape

(13223, 51)

In [390]:
len(data.iloc[:,1:data.shape[1]-1].columns)

49

In [391]:
df= data.iloc[:,1:data.shape[1]-1].apply(convert_prices,axis=0)
df['Date'] = data['Date']
data = df

In [392]:
len(data.iloc[:,0:data.shape[1]-1].columns)

49

In [393]:
def indicators_tech_closePriceOnly(price, date,name):
    '''
    Function that 

    @param price vector price vector
    @param date vector date corresponding to prices


    @return df dataframe with price and tech indicators 
    '''
    #convert vector to DataFrame
    df = pd.DataFrame({'price':price})
    df['Date']= date
    df['name']=name.strip()


    #add columns with indicators
    #Momentum indicators

    PPO = ta.momentum.PercentagePriceOscillator(price)
    df['ppo']=PPO.ppo()
    df['ppo_hist']=PPO.ppo_hist()
    df['ppo_signal']=PPO.ppo_signal()

    #Rate of Change (ROC)
    df['roc']=ta.momentum.ROCIndicator(price).roc()
    #Relative Strength Index (RSI)
    df['rsi']=ta.momentum.RSIIndicator(price).rsi()

    #Stochastic RSI
    StockRsi = ta.momentum.StochRSIIndicator(price)
    df['rsi_stoch']=StockRsi.stochrsi()
    df['rsi_stochrsi_d']=StockRsi.stochrsi_d()
    df['rsi_stochrsi_k']=StockRsi.stochrsi_k()

    #True strength index (TSI)
    df['tsi']=ta.momentum.TSIIndicator(price).tsi()

    #Kaufman’s Adaptive Moving Average (KAMA)
    df['kama']=ta.momentum.kama(price)

    #Volatility Indicators

    indicator_bb = ta.volatility.BollingerBands(price)
    df['bollinger_mavg']=indicator_bb.bollinger_mavg()
    df['bollinger_hband']=indicator_bb.bollinger_hband()
    df['bollinger_lband']=indicator_bb.bollinger_lband()

    df['bollinger_pband']=indicator_bb.bollinger_pband() 
    df['bollinger_wband']=indicator_bb.bollinger_wband() 

    #Ulcer Index
    df['ulcer']=ta.volatility.UlcerIndex(price).ulcer_index()

    #Volatility


    #Aroon Indicator
    indocator_aroon = ta.trend.AroonIndicator(price)
    df['aroon_down']=indocator_aroon.aroon_down()
    df['aroon_ind']=indocator_aroon.aroon_indicator()
    df['aroon_up']=indocator_aroon.aroon_up()

    #Detrended Price Oscillator (DPO)
    df['dpo']=ta.trend.DPOIndicator(price).dpo()

    #EMA - Exponential Moving Average
    df['ema']=ta.trend.EMAIndicator(price).ema_indicator()

    #KST Oscillator (KST Signal)
    indicator_kst = ta.trend.KSTIndicator(price)
    df['kst']=indicator_kst.kst()
    df['kst_diff']=indicator_kst.kst_diff()
    df['kst_sig']=indicator_kst.kst_sig()

    #MACD
    indicator_macd = ta.trend.MACD(price)
    df['macd']=indicator_macd.macd()
    df['macd_diff']=indicator_macd.macd_diff()
    df['macd_signal']=indicator_macd.macd_signal()

    #SMA Simple MA
    df['sma']=ta.trend.SMAIndicator(price,window=20).sma_indicator()

    #Schaff Trend Cycle
    df['stc']=ta.trend.STCIndicator(price).stc()

    #Trix
    df['trix']=ta.trend.TRIXIndicator(price).trix()

    #WMA Weighted MA
    df['wma']=ta.trend.WMAIndicator(price).wma()


    #return dataframe
    return df

In [394]:
portfolios = data.iloc[:,0:data.shape[1]-1].columns
portfolios

Index(['Agric', 'Food ', 'Soda ', 'Beer ', 'Smoke', 'Toys ', 'Fun  ', 'Books',
       'Hshld', 'Clths', 'Hlth ', 'MedEq', 'Drugs', 'Chems', 'Rubbr', 'Txtls',
       'BldMt', 'Cnstr', 'Steel', 'FabPr', 'Mach ', 'ElcEq', 'Autos', 'Aero ',
       'Ships', 'Guns ', 'Gold ', 'Mines', 'Coal ', 'Oil  ', 'Util ', 'Telcm',
       'PerSv', 'BusSv', 'Hardw', 'Softw', 'Chips', 'LabEq', 'Paper', 'Boxes',
       'Trans', 'Whlsl', 'Rtail', 'Meals', 'Banks', 'Insur', 'RlEst', 'Fin  ',
       'Other'],
      dtype='object')

In [395]:
data = data.reset_index()

In [490]:
df = None

for portf in portfolios:
    if df is None:
        df = indicators_tech_closePriceOnly(data[portf],data['Date'],name=portf)
    else:
        df = df.append(indicators_tech_closePriceOnly(data[portf],data['Date'],name=portf))

In [491]:
df = df[df['Date']>'1970-01-01'].sort_values(by="Date").reset_index()
df = df.iloc[:,1:]

In [492]:
df.iloc[1:].isnull().values.any()

False

,price,Date,name,ppo,ppo_hist,ppo_signal,roc,rsi,rsi_stoch,rsi_stochrsi_d,...,kst,kst_diff,kst_sig,macd,macd_diff,macd_signal,sma,stc,trix,wma
0,9.824296e+01,1970-01-02,Agric,-0.306046,0.188555,-0.494602,0.424064,56.816206,1.000000,0.382715,...,-13.033951,4.656384,-17.690335,-0.290366,0.179139,-0.469504,9.462507e+01,13.946340,-0.076818,9.432661e+01
1,9.715062e+01,1970-01-02,Hshld,-1.078363,0.677124,-1.755487,4.041015,55.847734,1.000000,0.973706,...,-65.654276,17.965069,-83.619345,-1.031823,0.657007,-1.688831,9.403354e+01,96.875000,-0.279694,9.479135e+01
2,9.487586e+01,1970-01-02,Whlsl,-1.270124,0.791392,-2.061515,5.347559,58.917243,1.000000,0.972533,...,-74.965451,20.634638,-95.600089,-1.174586,0.743762,-1.918348,9.062944e+01,96.875000,-0.325967,9.138325e+01
3,1.463428e+02,1970-01-02,Hlth,2.518139,0.993331,1.524808,9.197438,61.960207,0.897487,0.972073,...,44.965515,45.206458,-0.240942,3.489558,1.389952,2.099606,1.370222e+02,99.902344,0.185781,1.451470e+02
4,9.101243e+01,1970-01-02,Boxes,-1.160885,0.777764,-1.938649,4.652748,54.159321,1.000000,0.946209,...,-66.732770,24.563695,-91.296465,-1.044032,0.710927,-1.754959,8.807693e+01,99.023436,-0.305248,8.914808e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
641699,8.145695e+05,2021-11-30,Chems,-0.210618,-1.182603,0.971984,-9.426783,32.807038,0.000000,0.009948,...,34.493862,-37.362843,71.856705,-1805.826592,-10169.405373,8363.578781,8.753392e+05,0.195259,0.163894,8.453129e+05
641700,5.918970e+06,2021-11-30,BusSv,-0.976809,-0.966594,-0.010214,-8.394631,28.582674,0.000000,0.030460,...,1.410646,-29.195778,30.606424,-60960.510476,-60541.294615,-419.215861,6.331842e+06,0.195312,0.017658,6.094806e+06
641701,5.570613e+06,2021-11-30,Rubbr,-0.751442,-0.469890,-0.281552,-6.280064,28.123736,0.000000,0.023544,...,-6.250269,-11.858116,5.607847,-43834.637656,-27385.118261,-16449.519395,5.860234e+06,0.241461,-0.030565,5.749675e+06
641702,1.129613e+05,2021-11-30,Txtls,0.144264,-0.773791,0.918055,-5.826148,37.851169,0.000000,0.128133,...,32.412326,-11.865569,44.277895,170.354321,-914.851952,1085.206273,1.191294e+05,1.078130,0.144224,1.177193e+05
641703,5.173585e+05,2021-11-30,Other,-0.533831,-0.349022,-0.184809,-3.142227,39.219782,0.172869,0.192521,...,-2.243242,-14.994675,12.751433,-2808.771936,-1839.084660,-969.687276,5.302637e+05,0.195312,-0.014322,5.196817e+05

In [501]:
#used for testing if downloaded data are equal to original refida French49 dataset
int(np.mean(df.price)) == 263697

True