In [1]:
import pandas as pd
import ta

In [256]:
data = pd.read_csv('datasets/49_Industry_Portfolios_Daily.csv',skiprows=[0,1,2,3,4,5,6,7,8])

/Users/garvin/opt/anaconda3/envs/refinda/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3251: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [257]:
#exclude last entry indicating coopyrights
data = data.iloc[0:data.shape[0]-1]

#create date variable
data['Date'] = data.iloc[:,0]
#data['Index'] =  [i for i in range(data.shape[0])]


#drop unnamed column
data = data.drop(['Unnamed: 0'],axis=1)

In [258]:
data

,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,Clths,...,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other,Date
0,0.56,-0.07,-99.99,-1.39,0.0,-1.44,0.62,-1.27,-0.9,0.12,...,0.14,2.77,-0.02,0.27,0.59,0.47,0.81,0.57,-1.66,19260701
1,0.29,0.06,-99.99,0.78,0.7,1.46,0.03,0.0,-0.34,-0.35,...,0.07,0.0,0.01,-0.1,1.04,-0.03,-0.61,-1.03,3.09,19260702
2,-0.33,0.18,-99.99,-1.74,0.5,-0.96,-0.06,4.27,-1.2,0.41,...,-0.2,0.77,-0.22,-0.67,0.45,0.31,-0.72,0.62,1.41,19260706
3,3.57,-0.15,-99.99,-1.73,-0.12,-0.49,-0.06,-4.1,-0.22,0.16,...,0.18,-3.21,-0.57,-0.7,-1.09,0.21,0.07,0.17,0.62,19260707
4,0.3,1.12,-99.99,-0.15,0.3,-0.49,0.24,0.0,-0.01,0.79,...,0.46,-1.1,-0.38,0.33,0.99,-0.88,-0.36,-1.1,0.98,19260708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50249,0.16,-0.04,-4.0,0.57,0.36,-2.51,-0.99,0.32,-0.57,-1.07,...,-0.21,-0.14,-1.19,-0.6,0.65,0.09,-0.08,0.03,-0.22,20211123
50250,-0.03,-0.18,2.19,-0.37,-0.28,0.91,1.01,0.32,0.22,0.07,...,-0.09,0.35,-1.29,0.14,-0.1,-0.18,0.45,0.35,1.44,20211124
50251,-2.58,-1.97,-1.81,-0.95,-0.52,-1.38,-2.72,-2.69,-2.25,-3.13,...,-3.85,-2.77,-2.42,-3.0,-3.48,-2.78,-3.08,-3.17,-0.83,20211126
50252,-1.74,-0.83,-1.69,-0.02,-0.94,-1.73,-1.15,0.57,-1.03,-0.14,...,-0.42,-0.58,-0.66,-1.39,-0.47,-0.86,0.05,0.2,-0.07,20211129
50253,-1.99,-1.99,-3.0,-2.12,-0.55,-1.35,-2.03,-0.95,-2.4,-2.33,...,-2.7,-2.72,-2.5,-1.93,-1.28,-2.16,-1.75,-2.73,-0.35,20211130

In [260]:

#select equally weighted
data = data.iloc[25128:data.shape[0]]
data = data.reset_index()

In [261]:
data

,index,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,...,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other,Date
0,25128,0.63,-0.28,-99.99,-0.74,-0.04,-1.44,0.57,-1.27,-0.59,...,0.29,1.50,-0.13,-0.22,2.26,0.54,1.46,-0.11,-0.75,19260701
1,25129,1.03,0.11,-99.99,0.09,0.40,1.46,0.18,0.00,0.17,...,-0.51,0.00,-0.06,-0.86,0.94,-0.19,2.10,-0.68,2.47,19260702
2,25130,-1.26,-0.12,-99.99,-0.25,0.63,-0.96,0.09,4.27,-0.28,...,0.21,0.42,0.17,-0.28,0.25,0.69,-0.41,0.69,0.66,19260706
3,25131,1.55,-0.43,-99.99,-2.02,-0.76,-0.49,0.11,-4.10,-0.06,...,-0.14,-7.24,-0.41,-0.72,-0.84,0.13,-2.24,-0.41,0.41,19260707
4,25132,0.95,1.01,-99.99,-0.08,1.00,-0.49,-0.01,0.00,0.18,...,0.18,2.56,-0.29,-0.04,0.74,-0.83,-0.21,-1.15,-0.60,19260708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25121,50249,0.16,-0.04,-4.0,0.57,0.36,-2.51,-0.99,0.32,-0.57,...,-0.21,-0.14,-1.19,-0.6,0.65,0.09,-0.08,0.03,-0.22,20211123
25122,50250,-0.03,-0.18,2.19,-0.37,-0.28,0.91,1.01,0.32,0.22,...,-0.09,0.35,-1.29,0.14,-0.1,-0.18,0.45,0.35,1.44,20211124
25123,50251,-2.58,-1.97,-1.81,-0.95,-0.52,-1.38,-2.72,-2.69,-2.25,...,-3.85,-2.77,-2.42,-3.0,-3.48,-2.78,-3.08,-3.17,-0.83,20211126
25124,50252,-1.74,-0.83,-1.69,-0.02,-0.94,-1.73,-1.15,0.57,-1.03,...,-0.42,-0.58,-0.66,-1.39,-0.47,-0.86,0.05,0.2,-0.07,20211129
25125,50253,-1.99,-1.99,-3.0,-2.12,-0.55,-1.35,-2.03,-0.95,-2.4,...,-2.7,-2.72,-2.5,-1.93,-1.28,-2.16,-1.75,-2.73,-0.35,20211130

In [262]:
#converts all entries into floats and Date variable into TimeStemp
from datetime import datetime

for col in data.columns:
    if col != 'Date':
        data[col] = [float(str(x).strip()) for x in data[col].values]
    else:
        data[col] = [datetime.strptime(str(x).strip(), '%Y%m%d') for x in data[col].values]

In [263]:
data.head()

,index,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,...,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other,Date
0,25128.0,0.63,-0.28,-99.99,-0.74,-0.04,-1.44,0.57,-1.27,-0.59,...,0.29,1.50,-0.13,-0.22,2.26,0.54,1.46,-0.11,-0.75,1926-07-01
1,25129.0,1.03,0.11,-99.99,0.09,0.40,1.46,0.18,0.00,0.17,...,-0.51,0.00,-0.06,-0.86,0.94,-0.19,2.10,-0.68,2.47,1926-07-02
2,25130.0,-1.26,-0.12,-99.99,-0.25,0.63,-0.96,0.09,4.27,-0.28,...,0.21,0.42,0.17,-0.28,0.25,0.69,-0.41,0.69,0.66,1926-07-06
3,25131.0,1.55,-0.43,-99.99,-2.02,-0.76,-0.49,0.11,-4.10,-0.06,...,-0.14,-7.24,-0.41,-0.72,-0.84,0.13,-2.24,-0.41,0.41,1926-07-07
4,25132.0,0.95,1.01,-99.99,-0.08,1.00,-0.49,-0.01,0.00,0.18,...,0.18,2.56,-0.29,-0.04,0.74,-0.83,-0.21,-1.15,-0.60,1926-07-08

In [264]:
#make sure, no NA values present 
data.isnull().values.any()

False

In [265]:
from ta.volatility import BollingerBands
indicator_bb = BollingerBands(close=data["Agric"], window=20, window_dev=2)

In [267]:
# Add Bollinger Bands features
df['bb_bbm'] = indicator_bb.bollinger_mavg()
df['bb_bbh'] = indicator_bb.bollinger_hband()
df['bb_bbl'] = indicator_bb.bollinger_lband()

# Add Bollinger Band high indicator
df['bb_bbhi'] = indicator_bb.bollinger_hband_indicator()

# Add Bollinger Band low indicator
df['bb_bbli'] = indicator_bb.bollinger_lband_indicator()

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
          ...
25121    0.0730
25122    0.1065
25123   -0.1480
25124   -0.3020
25125   -0.4650
Name: mavg, Length: 25126, dtype: float64

In [271]:
ta.momentum.PercentagePriceOscillator(close=data["Agric"]).ppo_hist()

0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
            ...
25121    140.347118
25122     37.557068
25123   -272.945825
25124   -245.815450
25125   -212.119653
Name: PPO_hist_12_26, Length: 25126, dtype: float64